networks:
  default:
    driver: bridge 
    name: roboshop
  #external: true 

volumes:
  mongodb: 
  redis:
  mysql:
  rabbitmq:  # docker volume  

services:
  mongodb:
    image: nareshkumart/mongodb:v1
    container_name: mongodb
    volumes:
    - mongodb:/data/db 

  catalogue:
    image: nareshkumart/catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb
  redis:
    image: redis:7
    container_name: redis
    volumes:
    - redis:/data


  user:
    image: nareshkumart/user:v1
    container_name: user
    depends_on:
      - redis
      - mongodb
  cart:
    image: nareshkumart/cart:v1
    container_name: cart
    depends_on:
      - catalogue
      - redis
  mysql:
    image: nareshkumart/mysql:v1 
    container_name: mysql
    volumes:
    - mysql:/var/lib/mysql

  shipping:
    image: nareshkumart/shipping:v1 
    container_name: shipping
    depends_on: 
    - mysql
    - cart
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop 
      RABBITMQ_DEFAULT_PASS: roboshop123
    volumes:
    - /var/lib/rabbitmq
  payment:
    image: nareshkumart/payment:v1
    container_name: payment
    environment:
      CART_HOST: cart
      CART_PORT: 8080
      USER_HOST: user
      USER_PORT: 8080
      AMQP_HOST: rabbitmq
      AMQP_USER: roboshop
      AMQP_PASS: roboshop123
    depends_on:
      - cart
      - user
      - rabbitmq
  frontend:
    image: nareshkumart/frontend:v1
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - catalogue
      - cart
      - user
      - shipping
      - payment  

  



 